contract-addresses.json
migrations/2_deploy_contracts.js
scripts/allowTokens
scripts/allowedTokens

It seems there are some issues with the current version of the allowTokens and allowedTokens scripts, under the rif-relay-contracts repo.
It appears that:
network names are used during deployment (e.g. development) but IDs are used both in the contract-addresses.json file as well as the tokens scripts.
the allowedTokens script uses $2 as the network parameter name, instead of $1.
not all errors are displaying in the console in case something goes wrong.
Verify and fix this.
Also: update the Sample dApp readme so that the allow tokens section points to the rif-relay-contracts repo, once it works OK.

Fixes/pp 71/fix allow tokens scripts

---

contract-addresses.json
migrations/2_deploy_contracts.js
scripts/allowTokens
scripts/allowedTokens

Revert change that replace the id of the network to the name. This change is on migrate and contract-addresses.json.
On relaying services SDK have error because they not get the contract list from rif-relay-contracts contract-addresses file.
[Change the network name](https://rsklabs.atlassian.net/browse/PP-98)
Revert change on rif-relay-contracts to change the network name x the network id.
Modify the deploy migration and make this changes.

PP-98/Change the network name to network id

---

package.json

- Update the `@truffle/hdwallet-provider` package
- When we try to deploy the contracts on `testnet` the following error is raised: `"Migrations" -- Unknown Error: {"jsonrpc":"2.0","id":615502292974733,"error":{"code":-32602,"message":"Missing parameter, gasPrice, gas or value"}}`. After trying solutions, I discovered it could have been associated with the provider set in the testnet configuration, so I updated it to the latest version.

PP 95: Fix deploy on testnet

---

tasks/send-multisig.js
tasks/utils.js
tasks/withdraw.js

- Change the code that waits for the transaction receipt. Although that code was retrieved from the official documentation, it doesn't work as expected resulting in timing-related errors.
- We want to wait for the transaction receipt to be available otherwise, unexpected errors are raised showing that the transactions were not signed by other owners.

Fix the code that waits for the transaction receipt

---

contracts/smartwallet/CustomSmartWallet.sol
contracts/smartwallet/SmartWallet.sol
patches/@openeth+truffle-typings+0.0.6.patch

- Fix truffle typings patch
- Fix solhint warnings
- We may need to specify the `collectorContract` parameter, so we need to fix the type `Truffle.TransactionDetails` automatically generated by truffle.

PP-94: Fix truffle typings patch

---

tasks/utils.js

- Import the `revenue-sharing-addresses.json` file when required to avoid errors when executing `create-safe`.
- the file `revenue-sharing-addresses.json` is created when the collector is deployed, but we need to execute the `create-safe` script before and it requires `utils.js`. ATM `utils.js` requires the `revenue-sharing-addresses.json` file at the beginning, so if the file is missing, it raises an error.

PP-131/lazy-load-revenue-sharing-addresses

---

package.json
scripts/prepublishOnly
tsconfig.json

- Fix the build not to include the test folder
- Add the build step in the prepublish script
- The build includes the test folder
- We need to build the library before publishing it

PP 164: Add prepublish build

---

.mocharc.json
contracts/Collector.sol
deploy-collector.input.sample.json
package.json
tasks/deploy-collector.js
test/collector.test.ts
types/truffle-contracts/index.d.ts
waffle.json

- Modify the Collector contract to properly manage the remainder. It was done introducing an additional wallet where the remainder can be sent.
- Additionally, in this PR Waffle is introduced as testing framework and the Collector is fully covered with unit testing.
- Currently one can only update partners when token balance = 0, but due to how integer division works in solidity, it is very likely that there will be a remainder after distributing all fees to the partners. A token amount of 999 that needs to be distributed to 4 partners would leave a remainder of balance = 3 after withdrawal.
- [PP-130](https://rsklabs.atlassian.net/browse/PP-130)

PP-130-v2/remainder management

---

contracts/smartwallet/CustomSmartWallet.sol
test/factory/CustomSmartWalletFactory.test.ts
test/relayHub/RelayHub.test.ts
test/smartwallet/CustomSmartWallet.template.test.ts
test/smartwallet/customSmartWallet.test.ts
test/smartwallet/smartWallet.test.ts
test/utils.ts

- The problem is related to the fact that the initialize method of the template contract is never called, so a malicious attacker could call it and therefore set a logic address. After doing that, the attacker could call any function and that would lead the logic address to be executed. Potentially the logic address could contain a selfdestruct instruction that would destroy the template contract. If so, the proxies contracts won’t be able to execute any transaction anymore.
- I decided to just initialise the CustomSmartWallet implementation contract in the constructor.
- By using this approach the CustomSmartWallet initialization is blocked since the deployment to prevent malicious initialisation.
- [Jira issue](https://rsklabs.atlassian.net/browse/PP-325)

PP-325/REL-002

---

contracts/Ownable.sol
contracts/utils/VersionRegistry.sol
contracts/verifier/CustomSmartWalletDeployVerifier.sol
contracts/verifier/DeployVerifier.sol
contracts/verifier/RelayVerifier.sol

- Creates an abstract contract called Ownable and replaces all the implementations of Openzeppelin/Ownable
- The Openzeppelin implementation has not required functionalities that uses extra gas
- [PP-473](https://rsklabs.atlassian.net/browse/PP-473)

PP473: Replace Ownable with own ownership mechanism

---

.github/workflows/main.yml
contracts/factory/SmartWalletFactory.sol
contracts/smartwallet/SmartWallet.sol
test/factory/smartWalletFactory.test.ts
test/relayHub/RelayHub.test.ts
test/smartwallet/smartWallet.template.test.ts
test/smartwallet/smartWallet.test.ts

- We need to initialize the SmartWallet template to avoid security issues.
- If not initialized, an attacker could initialize it. Although this doesn't imply any security issue at the moment, it could open the attack surface to some social engineering attacks.
- It's a good practice initializing the contracts

PP-465: REL-002 - Initialize SmartWallet template

---

package.json

- Remove duplicated packages from `devDependencies`
- The package `"@truffle/hdwallet-provider": "1.2.4",` was outdated, so it was raising the following error:
> "Missing parameter, gasPrice, gas or value"
It has been already [fixed before](https://github.com/rsksmart/rif-relay-contracts/pull/12), but we missed the `devDependency` so the error appeared again.
- https://github.com/rsksmart/rif-relay-contracts/pull/12

Remove duplicated packages from devDependencies

---

package.json
scripts/removeTokens

script for removing tokens
utility script

PP-510: script for removing tokens

---

test/collector.test.ts

- Rewrite the unit tests for the Collector contract using Hardhat and Ethers.js
- Modernization of the project and quality improvements.
- [PP-478](https://rsklabs.atlassian.net/browse/PP-478)

PP-478: Rewrite collector tests

---

Readme.md
hardhat.config.ts
package.json
scripts/allowTokens.ts
scripts/deploy.ts
scripts/getAllowedTokens.ts
test/scripts/deploy.test.ts
test/scripts/getAllowedTokens.test.ts
utils/scripts/types.ts

- recreates the allowedTokens script in ethers/hardhat
- fix: missing customSmartWalletRelayVerifier contract on all scripts
- ethers migration
- (optional: include links to other issues, PRs, tickets, etc)

getAllowedToken task

---

contracts/interfaces/IWalletCustomLogic.sol
contracts/test/FailureCustomLogic.sol
contracts/test/ProxyCustomLogic.sol
contracts/test/SuccessCustomLogic.sol

- Update the interface of `IWalletCustomLogic` to reflect `IForwarder` changes
- The contracts `FailureCustomLogic.sol`,  `ProxyCustomLogic.sol`, `SuccessCustomLogic.sol`) are used in the integration tests and extends `IWalletCustomLogic`, so we need to update them in order to successfully call those contracts.

PP-513: fix IWalletCustomLogic interface to reflect IForwarder changes

---

test/smartwallet/CustomSmartWallet.template.test.ts
test/smartwallet/customSmartWallet.test.ts
test/smartwallet/smartWallet.template.test.ts
test/smartwallet/smartWallet.test.ts

- Rewrite unit test for SmartWallet contract in order to fix them.
-  The test were broken after the implementation of REL-002
- [PP-532](https://rsklabs.atlassian.net/browse/PP-532)

PP-532: fix SmartWallet unit tests broken by REL-002

---

contracts/Collector.sol
test/collector.test.ts

- Change the use of transfer from ERC20 to .call.
- Security bug found in REL-005.
- [PP-584](https://rsklabs.atlassian.net/browse/PP-584)

PP-584 (REL-005): Add secure transfer in the Collector

---

contracts/factory/CustomSmartWalletFactory.sol
contracts/factory/SmartWalletFactory.sol
contracts/smartwallet/CustomSmartWallet.sol
contracts/smartwallet/SmartWallet.sol
package-lock.json
package.json
test/factory/CustomSmartWalletFactory.test.ts
test/factory/smartWalletFactory.test.ts
test/factory/utils.ts
types/truffle-contracts/index.d.ts

This PR is a `rif-relay-contracts` port of @patogallaiovlabs's original PR from the `rif-relay` repo (see [here](https://github.com/rsksmart/rif-relay/pull/178)).
A PR with tests is available here.

PP-105: signature verification on createUserSmartWallet call

---

hardhat.config.ts
package-lock.json
package.json

- Change the configuration to read the custom signers to use from the environment, either by using an env variable or a `.env` file
- Without it, it's not possible to deploy to Testnet/Mainnet, because there wouldn't be any signer with balance
1. Either create a `.env` file or set the following env variables with a private key of an account you've control of ([Here](https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-export-an-account-s-private-key) a guide on how to export a private key from metamask)
2. Run the command `npx hardhat console --network testnet`
3. Run a simple transaction:
```
account  = (await ethers.getSigners())[0];
tx = await account.sendTransaction({to: 'address_will_receive_trbtc', value: ethers.utils.parseEther('0.01')});
```
4. Get the `tx.hash` …

PP-597: Change the configuration to use custom signers to run the script

---

contracts/factory/CustomSmartWalletFactory.sol
contracts/factory/SmartWalletFactory.sol
contracts/interfaces/IForwarder.sol
contracts/smartwallet/CustomSmartWallet.sol
contracts/smartwallet/SmartWallet.sol
contracts/test/TestUtil.sol
package-lock.json
package.json
test/factory/CustomSmartWalletFactory.test.ts
test/factory/smartWalletFactory.test.ts
test/relayHub/RelayHub.test.ts
test/smartwallet/customSmartWallet.test.ts
test/smartwallet/smartWallet.test.ts
test/utils.ts
test/verifier/customSmartWalletDeployVerifier.test.ts
test/verifier/deployVerifier.test.ts
test/verifier/relayVerifier.test.ts
types/EIP712/ForwardRequest.ts
types/EIP712/TypedRequestData.ts
types/truffle-contracts/index.d.ts

- add 'validUntilTime' field in forward and deploy request
https://rsklabs.atlassian.net/browse/PP-583
Unit tests inluded in this PR: https://github.com/rsksmart/rif-relay-contracts/pull/104

REL-004: expiration mechanism

---

.github/workflows/codeql.yml

- replace master with main on codeql workflow
- we don't use master any more.

PP-653: Fix github action

---

contracts/smartwallet/NativeHolderSmartWallet.sol
tasks/allowTokens.ts
tasks/deploy.ts
tasks/getAllowedTokens.ts
tasks/removeTokens.ts
tasks/utils.ts
test/smartwallet/nativeHolderSmartWallet.test.ts
test/smartwallet/smartWallet.test.ts
test/smartwallet/utils.ts
test/tasks/allowTokens.test.ts
test/tasks/deploy.test.ts
test/tasks/getAllowedTokens.test.ts
test/tasks/removeTokens.test.ts
test/tasks/utils.ts
utils/scripts/types.ts

- Migrate the NativeHolderSmartWallet tests to ethers
- Support the NativeHolderSmartWallet in the allowTokens and removeTokens script
- Rename directExecuteWithValue to directExecute
- Tests were written with truffle/web3

PP-669: Migrate the NativeHolderSmartWallet contract tests to ethers

---

Readme.md
hardhat.config.ts
tasks/withdraw.ts
test/tasks/withdraw.test.ts

- Modify withdraw script so it receives an additional optional parameter representing the token address to withdraw. If not sent, all allowed tokens will be withdrawn.
- Adapt the script to the recent Collector changes.
- [PP-720](https://rsklabs.atlassian.net/browse/PP-720)

PP720: Modify withdraw script to allow it to run with just one token

---

tasks/deploy.ts
test/tasks/deploy.test.ts

- do not raise an error when the address file is missing during the contracts deployment
- the error can be misleading and the developer could think that the deployment wasn't successful

fix(PP-804): do not show an error when the address file is missing

---

Readme.md
hardhat.config.ts
tasks/allowTokens.ts
tasks/getAllowedTokens.ts
tasks/removeTokens.ts
tasks/utils.ts
test/tasks/allowTokens.test.ts
test/tasks/getAllowedTokens.test.ts
test/tasks/removeTokens.test.ts

- change the allowed-tokens to receive the verifiers to check
- change the allow-tokens to receive the verifiers to modify
- to make the script more flexible and avoid asking for unnecessary data

PP-840: get allowed tokens for given verifiers only

---

tasks/withdraw.ts
test/tasks/withdraw.test.ts

- Wait for the transaction receipt while withdrawing funds from the collector.
- The previous balance was the same as the balance after the withdrawal, since we were not waiting the tx to be processed.

refactor(task/withdraw): wait for transaction receipt

---

contracts/factory/BoltzSmartWalletFactory.sol
contracts/factory/MinimalBoltzSmartWalletFactory.sol
contracts/factory/SmartWalletFactory.sol
contracts/smartwallet/BoltzSmartWallet.sol
package-lock.json
package.json

- Contract execution validation in boltz smart wallet initialization
- During estimation process without signature it is required to simplify the process

estimation-no-signature
