- Readme.md
- package.json
- tasks/mint.js
- Add a script to mint new TestToken
- Update readme to include mint script usage
> Add a new utility script to mint TestToken and to transfer it to a specific address

- contract-addresses.json
- Update the contract-addresses.json to include the Testnet deployment
- the latest version of the contracts were deployed on Testnet
- [PP-95](https://rsklabs.atlassian.net/browse/PP-95)
> Add Testnet addresses

- tasks/create-safe.js
- (describe the changes)
- (the reason these changes are wanted)
- (optional: include links to other issues, PRs, tickets, etc)
> Remove revenue-sharing-addresses usage to avoid circular depenencies

- contract-addresses.json
- migrations/3_revenue_sharing.js
- revenue-sharing-addresses.json
- tasks/create-safe.js
- tasks/safeFactory.json
- tasks/send-multisig.js
- tasks/utils.js
- tasks/withdraw.js
- Read the variable amount of partners from the file 'revenue-sharing-addresses.json'
- Apply prettier fixes.
- After [this PR](https://github.com/anarancio/rif-relay-contracts/pull/18), the script wasn't able to properly read the partner addresses.
> PP-122: Fix the withdraw script to reflect the changes applied to 'revenue-sharing-addresses.json'

- package.json
- test/basic-tests/chainId.test.ts
- Add the missing the dependency
- format the test files
- the missing dependency is causing an error when running the tests
> PP-148: Add the missing dependency and format the test file

- package.json
- publish the `contracts/test` folder
- the `contracts/test` folder includes some contracts useful for testing purposes.
> PP-271: Include contracts/test to allow the test execution

- truffle.js
- Add a network to be used in circleci
- Because it's required to run the integration tests
> Fix circleci

- package.json
- Update the package version
- Release a new version to be used in the integration tests
> 0.0.2 alpha.8

- package.json
- test/relayHub/RelayHub.test.ts
- test/utils.ts
- Tests for the RelayHub contract
- Increase test coverage over contracts
> PP-199: RelayHub contract tests

- index.ts
- Integration of price feeder for RBTC-RIF
- Needed for revenue sharing validation process
- [PR #288 (Implement a token-RBTC conversion)](https://rsklabs.atlassian.net/browse/PP-288)
> PP-288/rif-rbtc

- test/verifier/customSmartWalletDeployVerifier.test.ts
- test/verifier/deployVerifier.test.ts
- unit tests for deploy verifier contract in hardhat/ethers
- Upgrading to hardhat
- PP-432
> Hardhat tests on Deploy Verifier PP-432

- hardhat.config.ts
- package.json
- test/verifier/customSmartWalletDeployVerifier.test.ts
- test/verifier/deployVerifier.test.ts
- test/verifier/relayVerifier.test.ts
Recreate unit tests on Relay Verifier
Need to change to hardhat + ethers js
PP-432
> PP-433 Hardhat Tests on Relay Verifier

- test/smartwallet/smartWallet.test.ts
- test/utils/EIP712Utils.ts
- Add unit tests for SmartWallet contract
- Increase product quality
- [PP-430](https://rsklabs.atlassian.net/browse/PP-430)
> PP-430: Test for smartWallet contract

- contracts/Collector.sol
- contracts/factory/CustomSmartWalletFactory.sol
- contracts/factory/SmartWalletFactory.sol
- contracts/interfaces/ICollector.sol
- package-lock.json
- package.json
- test/collector.test.ts
- test/factory/CustomSmartWalletFactory.test.ts
- test/relayHub/RelayHub.test.ts
- test/smartwallet/smartWallet.test.ts
- test/utils.ts
- test/verifier/customSmartWalletDeployVerifier.test.ts
- test/verifier/deployVerifier.test.ts
- test/verifier/relayVerifier.test.ts
- types/EIP712/TypedRequestData.ts
- ~~Removing feeReceiver~~
- Changes on methods to optimise gas consumption 
- The primary objective of RIF Relay is to relay transaction the cheapest way possible.
- [Jira](https://rsklabs.atlassian.net/browse/PP-450)
> PP-450/optimise-gas-consumption-v2

- package-lock.json
- package.json
- Tag a new release of the contracts.
- It includes the revenue sharing feature.
> v1.0.0-alpha.0

- contracts/verifier/CustomSmartWalletDeployVerifier.sol
- contracts/verifier/DeployVerifier.sol
- contracts/verifier/RelayVerifier.sol
method to remove tokens from acceptedTokens array
Functionally there needs to exist a counterpart to acceptToken()
tests contained in:
https://github.com/rsksmart/rif-relay-contracts/pull/79
> PP-509: add the removeToken method

- .github/workflows/slither.yml
- Adds a new slither.yml github-actions workflow. Slither is a solidity static code analyzer for finding security issues in smart contracts. This workflow is configured to run for any changes in the `contracts/` folder. Changes under `contracts/test` are ignored and test Solidity files are not included in the scan. Output of the scan will be available in the [Security > Code Scanning](https://github.com/rsksmart/rif-relay-contracts/security/code-scanning) tab. 
- This is useful for automatically triggering security scans. One use case would be to resolve the security findings reported by the tool prior to a full security audit.  
- Findings are uploaded to the Github Security Page which makes it possible to track the findings more easily. If the finding is marked as false-positive or …
> Add slither workflow for scanning security issues.

- contracts/verifier/CustomSmartWalletDeployVerifier.sol
- contracts/verifier/DeployVerifier.sol
- contracts/verifier/RelayVerifier.sol
- test/verifier/customSmartWalletDeployVerifier.test.ts
- test/verifier/deployVerifier.test.ts
- test/verifier/relayVerifier.test.ts
- implement removeToken()
- A method to delist tokens from rif-relay was needed
> PP-509 remove tokens from acceptedTokens array

- package-lock.json
- package.json
- Update `package.json` and `package-lock.json`
- Change the package version
> v1.0.0-alpha.1

- contracts/Collector.sol
- index.ts
- types/truffle-contracts/index.d.ts
- Expose the partners structure in the collector contract
- To interact with the structure where is needed
- [Jira 504](https://rsklabs.atlassian.net/browse/PP-504)
> PP-504/remove-worker-configuration

- contracts/factory/CustomSmartWalletFactory.sol
- contracts/factory/SmartWalletFactory.sol
- contracts/interfaces/IForwarder.sol
- contracts/smartwallet/CustomSmartWallet.sol
- contracts/smartwallet/SmartWallet.sol
- test/relayHub/relayHubContractScenarios.test.ts
- test/smartwallet/customSmartWallet.test.ts
- test/smartwallet/smartWallet.test.ts
- test/utils/EIP712Utils.ts
- test/verifier/customSmartWalletDeployVerifier.test.ts
- test/verifier/deployVerifier.test.ts
- test/verifier/relayVerifier.test.ts
- expiration mechanism
https://rsklabs.atlassian.net/jira/software/projects/PP/boards/84/backlog?selectedIssue=PP-583
- (optional: include links to other issues, PRs, tickets, etc)
https://github.com/rsksmart/rif-relay-contracts/pull/102
> feat: expiration mechanism

- .github/workflows/codeql.yml
- contract-addresses.json
- contracts/interfaces/IForwarder.sol
- contracts/smartwallet/CustomSmartWallet.sol
- contracts/smartwallet/NativeHolderSmartWallet.sol
- contracts/smartwallet/SmartWallet.sol
- migrations/2_deploy_contracts.js
- test/relayHub/RelayHub.test.ts
- test/smartwallet/customSmartWallet.test.ts
- test/smartwallet/nativeHolderSmartWallet.test.ts
- test/smartwallet/smartWallet.test.ts
- test/utils.ts
- test/verifier/relayVerifier.test.ts
- types/truffle-contracts/index.d.ts
- types/truffle-contracts/merge.d.ts
- Create a new SW that doesn’t automatically transfer RBTC to the owner (EOA)
- Extra implementation needed by the  User Services team 
- [PP-642](https://rsklabs.atlassian.net/browse/PP-662)
> PP-642/implement-new-sw

- Readme.md
- describe how to specify an account for the testnet deployment
- It's missing in Readme.md
> PP-675: describe how to specify an account for the deployment

- .github/workflows/contracts-cd.qa.yml
- .github/workflows/contracts-cd.rwm.yml
- .github/workflows/contracts-cd.rwt.yml
- .github/workflows/contracts-cd.testnet.yml
- hardhat.config.ts
- Apart from the server register step, this is the only step that is performed manually. We want to automate this. In the same way we did for the other libraries.
- Currently still a manual process.
> Automate the contracts deployment

- test/collector.test.ts
- test/penalizer/Penalizer.test.ts
- test/relayHub/relayHubContractScenarios.test.ts
- test/smartwallet/CustomSmartWallet.template.test.ts
- test/smartwallet/customSmartWallet.test.ts
- test/smartwallet/smartWallet.template.test.ts
- test/smartwallet/smartWallet.test.ts
- test/tasks/allowTokens.test.ts
- test/tasks/deploy.test.ts
- test/tasks/getAllowedTokens.test.ts
- test/verifier/customSmartWalletDeployVerifier.test.ts
- test/verifier/deployVerifier.test.ts
- test/verifier/relayVerifier.test.ts
- Enable the property noUncheckedIndexAccess in the tsconfig.json.
- Avoid having it globally disabled
- (PP-678)[https://rsklabs.atlassian.net/browse/PP-678]
> PP-678/noUncheckedIndexAccess

- package-lock.json
- package.json
- test/factory/smartWalletFactory.test.ts
- test/factory/utils.ts
- test/smartwallet/customSmartWallet.test.ts
- Migrate SmartWalletFactory unit testing
- Part of the web3 to ethers migration
- [PP-670](https://rsklabs.atlassian.net/browse/PP-670)
> PP-670/smart-wallet-factory-migration

- .github/workflows/slither.yml
- contracts/factory/SmartWalletFactory.sol
- fix the upload sarif file github action
- it's currently failing 
- https://github.com/rsksmart/rif-relay-contracts/actions/runs/7880836864/job/21503484509?pr=149
> PP-887: add job permissions

- .solhint.json
- contracts/DestinationContractHandler.sol
- contracts/TokenHandler.sol
- contracts/factory/BaseSmartWalletFactory.sol
- contracts/factory/BoltzSmartWalletFactory.sol
- contracts/factory/CustomSmartWalletFactory.sol
- contracts/factory/MinimalBoltzSmartWalletFactory.sol
- contracts/factory/SmartWalletFactory.sol
- contracts/interfaces/ICreateCustomSmartWalletFactory.sol
- contracts/interfaces/ICreateSmartWalletFactory.sol
- contracts/interfaces/IRelayerSmartWalletFactory.sol
- contracts/interfaces/ISmartWalletRelayer.sol
- contracts/interfaces/IWalletFactory.sol
- contracts/smartwallet/BaseSmartWallet.sol
- contracts/smartwallet/BoltzSmartWallet.sol
- contracts/smartwallet/MinimalBoltzSmartWallet.sol
- contracts/smartwallet/SmartWallet.sol
- contracts/utils/Eip712Library.sol
- contracts/verifier/MinimalBoltzDeployVerifier.sol
- As a developer, I want to remove the code duplication, so that the repo will be easier to maintain.
- Duplicated code
-  [PP-888](https://rsklabs.atlassian.net/browse/PP-888)
-  [PP-889](https://rsklabs.atlassian.net/browse/PP-889)
-  [PP-890](https://rsklabs.atlassian.net/browse/PP-890)
> PP-888/contract-abstraction

- package-lock.json
- package.json
- Update the package version
- To release a new package
> chore: update the package version

- contracts/smartwallet/BoltzSmartWallet.sol
- contracts/smartwallet/CustomSmartWallet.sol
- contracts/smartwallet/MinimalBoltzSmartWallet.sol
- contracts/smartwallet/SmartWallet.sol
- remove invalid comments
- they can be misleading and bring unclarity
> fix(RREL-024): remove invalid comments

- contracts/smartwallet/MinimalBoltzSmartWallet.sol
- package-lock.json
- package.json
- test/penalizer/Penalizer.test.ts
- test/tasks/collector/deployCollector.test.ts
- test/tasks/deploy.test.ts
- test/tasks/destinationContractHandler/removeContracts.test.ts
- test/tasks/tokenHandler/removeTokens.test.ts
- Contract execution validation in minimal boltz smart wallet initialization
- During estimation process without signature, it is required to simplify the process
> estimation-no-signature
